#!/bin/bash
echo "Test de $1..."
i=1
while [ $i -lt 1000000 ]; do
    for j in `seq 1 10`; do
        systime=$(/usr/bin/time -f %e $1 $i)
        echo -e "Temps pour i=$i:\n$systime"
    done
    let i*=2
done